- plugins/http/http_listen_input.go
Found a typo in HttpListenInput.
Maybe it would be even better to return from the function when it can't read the request body?
> Fix log typo in HttpListenInput

- logstreamer/reader.go
(http://en.wikipedia.org/wiki/Gzip#File_format) instead of relying on
the file name ending in .gz.
This makes it possible to use heka with svlogd (part of runit), when
svlogd compresses older log files, as svlogd does not change the
original file name.
> Detect gzip files using the first two magic bytes in the file

- CHANGES.txt
- docs/source/config/outputs/elasticsearch.rst
- plugins/elasticsearch/elasticsearch.go
This code is very similar to the way AMQP plugin works.  It checks to see if the server is using https protocol.  If so, TLS is enabled.  Currently, ES does not support TLS on its own, but TLS can be accomplished by proxying it with Apache or Nginx.
There will be another product of ES in the future called the Shield which will support TLS (and other security related stuff).  Presumably this code will also work for people who decide to use Shield.
http://www.elasticsearch.org/overview/shield
> add tls support to ES

- docs/source/config/inputs/httplisten.rst
- plugins/http/http_listen_input.go
- plugins/http/http_listen_input_test.go
Follow-up to #1267
This PR makes it possible to include http request headers in HttpListenInput. If the configured headers are found, they are added as message fields.
(I also cleaned up the logging a bit since hli.ir.LogMessage already prefix the log message with the plugin name.)
> HttpListenInput: Add ability to include headers as fields

- docs/source/config/inputs/httplisten.rst
The query parameter feature was added to Heka 0.6, but is not mentioned in the docs.
> HttpListenInput: document query parameter feature

- CHANGES.txt
- pipeline/stat_accum_input.go
- pipeline/stat_accum_input_test.go
For issue #850 based on @alexzorkin changes, just added a line to CHANGES.txt and did not change the print format line. I believe the %f is the correct format type to use in this case.
> Treat gauges as floats for statsd input, fixes #850

- CHANGES.txt
- docs/source/config/outputs/elasticsearch.rst
- docs/source/config/outputs/tcp.rst
- pipeline/buffered_output.go
- plugins/elasticsearch/elasticsearch.go
- plugins/tcp/tcp_output.go
As discussed on the Heka mailinglist, this is a commit to introduce a
use_buffering mode to the ElasticSearch output plugin. It changes the default
behavior to buffer to disk, like the TCP Output plugin, with all the other
options of the TCP Output plugin and the additional option to set use_buffering
to false to disable it (this just dumps any failed packets to nowhere, though -
no retry logic).
This also buffers in "chunks" rather than individual messages, so there still
is the tiny possibility that if a message has been received and hasn't filled
the commit buffer yet, it can be lost if Heka dies, but the default commit
buffer is sent every 1 second so this state is a lot better than quietly
dropping messages if they fail to send even once.
> Add disk-based buffering for ElasticSearch output

- CHANGES.txt
- plugins/statsd/statsd_input.go
- plugins/statsd/statsd_input_test.go
Some statsd emitters put a double \n\n in the output of multi line statsd stats.  This causes the entire message to be treated as failed, when there is an easy fix here.  Same behavior as statsd itself https://github.com/etsy/statsd/blob/master/stats.js line  205 or so.
> Handle multi-line statsd input more like statsd

- CHANGES.txt
- plugins/smtp/all_spec_test.go
- plugins/smtp/encoder.go
- plugins/smtp/encoder_test.go
- plugins/smtp/smtp_output.go
- plugins/smtp/smtp_output_test.go
Email headers must contain only ASCII characters.
http://ncona.com/2011/06/using-utf-8-characters-on-an-e-mail-subject/
> SmtpOutput: encode email subject with base64

- cmake/externals.cmake
- docs/source/config/inputs/docker_log.rst
- plugins/docker/attacher.go
- plugins/docker/client.go
- plugins/docker/docker_log_input.go
This solves #1279 
Support for TLS is now implemented in the upstream go-dockerclient. Unfortunately, they are nowadays depending on docker/docker and therefore also Sirupsen/logrus, meaning that we need to add those to externals.cmake if we want to use upstream. I think that is a bit silly, since we're only using a small fraction of the API.
Instead, I patched away the functions depending on it here: https://github.com/carlanton/go-dockerclient/commit/d408f209d5946d86da69382b3eb0a6faac7b3885
> Add TLS support for DockerLogInput

- docs/source/glossary.rst
Fixes two references to there only being 4 types of plugins - looks like this predates Encoders and Splitters.
> Correct out of date Plugin descriptions in Glossary

- pipeline/splitter_runner.go
- pipeline/splitter_runner_test.go
In order to be able to reuse a SplitterRunner on a new stream, we need a mechanism to reset the state about the stream.
In order to "tail" a stream that could return EOF, but later have more data to read, we also reset the "reachedEOF" parameter after we return the final record in the stream. That will cause the next subsequent request for a record to re-read the underlying stream. Note that this is *not* sufficient for the "new stream" situation above, where we want to discard any leftover data (as well as state) from the previous stream.
> Add a "reset" mechanism for SplitterRunners.

- CHANGES.txt
- plugins/kafka/kafka_input.go
- plugins/kafka/kafka_input_test.go
An offset of 0 is not always valid, so use oldest instead.
> Fix Kafka behavior with manual offset when checkpoint file doesn't exist

- sandbox/lua/filters/heartbeat.lua
Heartbeat monitoring per host.
Generates a JSON structure that can be used to create a custom heartbeat dashboard.
The output consists of a row per host which includes the host's 
last_heartbeat, last_alert and status.
This plugin also sends an alert when the heartbeat_timeout is exceeded and
supports alert throttling to reduce noise.
> Add heartbeat filter

- CHANGES.txt
- sandbox/lua/encoders/schema_influx.lua
messages as an array of series as opposed to the default which is a
single series with each field as a separate column.  This is a
recommended format for performance reasons in v0.9.0+ as documented here:
http://influxdb.com/docs/v0.8/advanced_topics/schema_design.html#migration-to-0.9.0
> Adding functionality to the schema_influx.lua script to structure

- plugins/amqp/amqp_input.go
- plugins/amqp/amqp_output.go
- plugins/amqp/types.go
- `AMQPDialer{tlsConfig}` => `NewAMQPDialer(tlsConfig)`
- `getAmqpHub()` => `GetAmqpHub()`
By exposing this functionality, custom external plugins can be written that utilize the same connection methodology as the embedded plugin but can customize the parsing and routing technique on a per use-case basis.
This is a small PR and fairly straight forward, but if I missed anything please let me know.
> plugins[amqp]: expose "types" hub and dialer methods

- pipeline/pipeline_runner.go
- plugins/tcp/tcp_input.go
- plugins/udp/udp_input.go
- plugins/udp/udp_input_test.go
Since the Splitter code landed, the "Type" field is no longer getting set by the TcpInput and UdpInput.
If it wasn't intentional, please consider this PR to reinstate it :)
(I changed the value of the Type slightly to match what some of the others looked like - ie; lowercase, prefixed with 'heka.')
Also tweaked the formatting for the startup messages to calm my OCD.
> Set Type on Tcp and Udp Input's

- docs/source/config/inputs/process.rst
Also clarify that ticker_interval is ignored when run under a ProcessDirectoryInput.
> Remove 'trim' config option.

- CHANGES.txt
- docs/source/config/inputs/amqp.rst
- plugins/amqp/amqp_input.go
This adds a configuration option, ReadOnly, to AMQP input to
allow users which only have read access to connect to a queue.
The exchange, queue, and binding must be declared prior to
starting heka with a read-only user.
The config option defaults to false. Fixes #1314.
> Enable AMQP input to use a read-only user

- pipeline/plugin_runners.go
A SandboxFilter dying in 0.9 causes Heka to shut down, regardless of the "can_exit" config (added in #962).
It looks like the plumbing between the config and the runner may have wandered off?  This should fix it...
> Add back CanExit plumbing

- plugins/http/http_listen_input.go
- plugins/http/http_listen_input_test.go
> Always concatenate until we get to an EOF error when a

- pipeline/buffered_output.go
- pipeline/splitter_runner.go
> Don't set reachedEOF flag unless we're not going to return the

- plugins/file/file_polling_input.go
- plugins/file/file_polling_input_test.go
Looks like changes from 1b211c67108c390df907d9ae667f1c2467446238 stopped the file_polling_input from supplying the hostname in the message.  I'm happy to provide some additional tests along with this PR if desired.
> Set hostname in FilePollingInput plugin

- cmd/heka-cat/main.go
This lets heka-cat work with messages larger than the default 64k. A 4MB maximum is probably overkill, but it should have minimal impact as long as the actual messages encountered are small.
> Add configurable max message size to heka-cat

- message/message.go
- sandbox/lua/lua_sandbox.go.in
- sandbox/lua/lua_sandbox_interface.c
- sandbox/lua/lua_sandbox_test.go
- sandbox/lua/testsupport/write_message_decoder.lua
- sandbox/lua/testsupport/write_message_errors.lua
- sandbox/plugins/sandbox_decoders_test.go
Allows deletion of field values in decoders through `write_message("fieldname", nil)`, as suggested in #842 
I implemented this as a workaround for #1295. With this PR a field can be overwritten by a value of different type by deleting it first.
> delete field values through write_message with nil, fixes #842

- plugins/dasher/dashboard_output.go
Go's `make` builtin allocates memory for a new object; a map of
HTTP headers in this case.
According to the [documentation][] for `make`, memory is allocated for map
types even if the map size is omitted:
> Map: An initial allocation is made according to the size but the
> resulting map has length 0. The size may be omitted, in which case a
> small starting size is allocated.
We can safely omit the `Headers` field entirely here and avoid
unnecessarily allocating memory.
[documentation]: http://golang.org/pkg/builtin/#make
> Dashboard: Avoid unnecessary memory allocation

- CHANGES.txt
- plugins/dasher/dashboard_output.go
Close the file once we've finished writing to it.
> Dashboard: Close plugin list file

- docs/source/getting_started.rst
Backslash-escaping: bane of programmers throughout history.
> docs: Fix two typos.

- docs/source/config/filters/stat.rst
- plugins/statsd/stat_filter.go
Useful when this filter runs with graphite.
Because graphite use a dot as a namespace separator.
And so, if a Type for exmeple contains a dot, it will
mess up the graphite storage.
note: I'm a real beginner with golang. I'm sure the code could be better ;)
> Added a config flag to replace all dots in stats filters

- CHANGES.txt
- docs/source/config/index.rst
- docs/source/config/inputs/index.rst
- docs/source/config/inputs/process.rst
- docs/source/config/inputs/processdir.rst
- docs/source/developing/plugin.rst
- pipeline/config.go
- pipeline/plugin_runners.go
- pipeline/plugin_runners_test.go
- plugins/process/process_chain.go
- plugins/process/process_directory_input.go
- plugins/process/process_input.go
- plugins/process/process_input_test.go
* Honour retry config regardless of ticker_interval, or whether spawned from a
ProcessDirectoryInput (for #1412 and #1418)
* Plugins exiting cleanly will not be subject to Retries
* Make InputRunners support can_exit (defaults to false, ProcessDirectoryInput
spawned processes default to true).  Skipped if runner was removed
deliberately (ie; on a ProcessDirectoryInput config change)
* ProcessInput spawned commands pass exit error back up to plugin_runner.
* Reset the stopChan, once mutex, exitError and cc in Run rather than Init (so
ProcessDirectoryInput commands spawned after a config change have a fresh
start)
* Doc + some test updates (could do with more improvement)
> Retry logic changes for Inputs

- CHANGES.txt
- logstreamer/reader.go
For the old codes, in some case, like `seekPos` is large enough, may cause an OOM exception.
And then, `ioutil.Discard` will grab a `[]byte` from `blackHolePool`, it may relieve gc's pressure,
Landing in the 0.9.2 release.
> Fix a gziped file seeking in log streamer may cause an OOM exception

- CHANGES.txt
- pipeline/pipeline_runner.go
- pipeline/plugin_runners.go
for IsStoppable on all input, filter, output plugins to decide
whether startup failure should cause Heka to exit. Fixes #1439.
> Check for decoder existence when decoder is specified, check

- CHANGES.txt
- plugins/http/http_output.go
Some servers choose to send chunked responses which have no Content-Length header (ie; one implemented in Go will default to this unless you set a Content-Length header yourself).
> Handle chunked error responses in http_output

- CHANGES.txt
- docs/source/config/encoders/esjson.rst
- plugins/elasticsearch/encoders.go
- plugins/elasticsearch/encoders_test.go
This make it possible to set custom field names in ES, like:
[ESJsonEncoder]
...
[ESJsonEncoder.field_mapping]
Timestamp = "@timestamp"
EnvVersion = @version"
Logger = "source"
Would you be interested in merging this after some docs and tests has been written?
> Make it possible to change field names for ESJsonEncoder

- CHANGES.txt
- pipeline/plugin_runners_test.go
- pipeline/stat_accum_input.go
- pipeline/stat_accum_input_test.go
I suppose ticker_interval in Stat Accumulator Input should be greater than 0.
Mistakenly setting this value to 0 would break the Accumulator, and possibly divided by 0 error.
This pull requests resolves #1474.
> ticker_interval in Stat Accumulator Input must be greater than 0.

- sandbox/lua/filters/http_status.lua
Default of 3600 which is the same as the default in the anomaly module
> Add optional alert_throttle config to the http_status filter

- CHANGES.txt
- sandbox/lua/encoders/es_payload.lua
Below is the tcpflow output without the newline:
```
POST /_bulk HTTP/1.1
Host: 172.17.0.36:9200
User-Agent: Go 1.1 package http
Content-Length: 97
Accept: application/json
Accept-Encoding: gzip
{"index":{"_index":"2015.03.31","_type":"7d98073d388e"}}
{"bar":"boo","log":"awesome"}
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=UTF-8
Content-Length: 99
{"error":"ActionRequestValidationException[Validation Failed: 1: no requests added;]","status":400}
```
> ElasticSearch bulk api expects newline in the end of the payload

- CHANGES.txt
- plugins/elasticsearch/elasticsearch.go
know the HTTP request went through.
> Never retry a buffered record for ElasticSearch over HTTP if we

- CHANGES.txt
- logstreamer/filehandling.go
> Make sure we actually use the result of the FilterOld call. Fixes

- CHANGES.txt
- pipeline/buffered_output.go
- pipeline/buffered_output_test.go
- plugins/tcp/tcp_output.go
'drop' as the queue_full_action, fixes #1484.
> Fix TcpOutput recovery from full queue when using 'block' or

- CHANGES.txt
- plugins/elasticsearch/elasticsearch.go
down during queue full situations.
> ElasticSearchOutput now correctly recovers from and shuts

- pipeline/splitter_runner.go
- sandbox/plugins/sandbox_decoder.go
- sandbox/plugins/sandbox_decoders_test.go
original message after deserializing from protobuf.
> Invalidate MsgBytes if the SandboxDecoder copies headers from

- CHANGES.txt
- cmake/externals.cmake
- docs/source/config/outputs/file.rst
- plugins/file/file_output.go
- plugins/file/file_output_test.go
@rafrombrc @trink could you look at this? Test passes, but second pair of critical eyes will be appreciated (as always).
> Using stftime literals for filenames during rotation in FileOutput plugin (#1469)

- docs/source/config/inputs/httplisten.rst
pretty sure this was probably copied over from the origin HTTP input plugin.
> request body instead?

- plugins/process/process_input.go
ProcessInput deadlock when subcommand returns non-0
Instead of return, input should send true to stopChan:
process_input.go line 290
if pi.exitError != nil {
pi.stopChan <- true
return
}
Will send a pull request.
> #1522, ProcessInput deadlock when subcommand returns non-0.

- CHANGES.txt
- pipeline/pipeline_runner.go
- pipeline/plugin_maker.go
remove debug output, send "stopping decoder" output to stdout
instead of stderr. Fixes #1531.
> Use lock and clean up decoder list during pipeline shutdown,

- CHANGES.txt
- docs/source/config/inputs/docker_log.rst
- plugins/docker/attacher.go
- plugins/docker/docker_log_input.go
This pull request allow to set in the DockerLogInput a configuration to set the ContainerName using an arbitrary environment variable defined inside the container. Refers to issue https://github.com/mozilla-services/heka/issues/1545
If the environment variable defined on the configuration is not set, it uses the ContainerName instead.
Added on the configuration a new entry name_from_env_var that allows to select the desired variable to use.
Sample configuration: 
(This sample is useful to get the mesos task id instead of the container name, since using Mesos/Marathon the container name does not match the marathon id)
```toml
[hekad]
maxprocs = 2
[Dashboard]
type = "DashboardOutput"
address = ":4352"
ticker_interval = 15
[DockerLogInput]
name_from_env_var = "MESOS_TASK_ID"
[influxdb]
type …
```
> Allow to overwrite the ContainerName using a Container Environment Variable. Issue 1545

- cmd/heka-cat/main.go
When outputting the data to stdout the status messages corrupt the
data stream.
> Don't write the status messages to stdout

- plugins/process/process_input.go
- plugins/process/process_input_test.go
Pack decorator should wait for command chain to finish processing.
> ProcessInput returns incorrect exit status

- CHANGES.txt
- plugins/elasticsearch/elasticsearch.go
ElasticSearchOutput's server configuration uses the spec, host,
and port (e.g. "http://localhost:9200") but ignores the path.
"http://localhost/es/" becomes "http://localhost/". The path value was
already in the structure parsed by the go url lib and needed to be tracked
and added to the HTTP request URL.
> Support for path in elasticsearch server config

- pipeline/splitter_runner.go
Only if there's more data to read and there's no error.
Continue rather than attempting to deliver an empty record.
> Stop zero-length records with no error ending the splitter (#1561)

- CHANGES.txt
- docs/source/config/encoders/esjson.rst
- plugins/elasticsearch/encoders.go
This pull request addresses feedback from #1596.
I have been using the Fields structure to store information for my sandbox plugins and I needed to select just one field for output. The current approach is all or nothing, you can choose to send all "Fields" values or you can choose to send none. I add a new configuration value called "DynamicFields" which lets you specify properties, which if present, will be put in the JSON object. This also support raw encoding of DynamicFields values through "RawBytesFields".
Do not merge: does not yet support the ESLogstashV0Encoder.
> ES dynamic_fields

- CHANGES.txt
- pipeline/queue_buffer.go
max size of a message (fixes #1623).
> Don't start if buffer max file size is too small to hold the

- sandbox/lua/decoders/nginx_error.lua
This PR makes the `nginx_error` decoder accept the `type` configuration parameter, just like the `nginx_access` decoder.  Note that the default value here is `"nginx.error"` instead of `nil` in order to keep compatibility with previous behavior of unconditionally setting the type to `"nginx.error"`.
> Allow configuring a custom message type in nginx_error decoder.

- plugins/process/process_input.go
This was lost in https://github.com/mozilla-services/heka/commit/1b211c67108c390df907d9ae667f1c2467446238#diff-a198f6754fbc5183d535aebc4885003eL434
> Output stream errors

- CHANGES.txt
- plugins/process/process_input.go
- plugins/process/process_input_test.go
Fix #1620 and  #1644. Unnecessary waiting from decorator, it's only invoked after the input is parsed and handled.
> Fix #1620, #1644. Unnecessary waiting from decorator.

- docs/source/config/encoders/payload.rst
> Update payload encoder docs to reflect use of strftime syntax to

- CHANGES.txt
- pipeline/splitter_runner.go
- pipeline/splitter_runner_test.go
- plugins/http/http_input.go
- plugins/http/http_input_test.go
- plugins/http/http_listen_input.go
- plugins/http/http_listen_input_test.go
- plugins/http/http_util.go
- plugins/process/process_input.go
- plugins/process/process_input_test.go
interface, updated HttpInput, HttpListenInput, ProcessInput to
use it. Fixes #1645.
> Added `SplitStreamNullSplitterToEOF` to SplitterRunner

- docs/source/sandbox/manager.rst
settings in sbmgr tutorial. Fixes #1660.
> Trivial clean-ups and removal of outdated TcpInput config

- CHANGES.txt
- docs/source/config/outputs/tcp.rst
- plugins/tcp/tcp_output.go
This feature would be useful in a couple of places:
* For destinations that only support 1 payload per TCP connection, like the [Zabbix agent "active check"](https://www.zabbix.com/documentation/2.4/manual/appendix/items/activepassive) protocol, which closes the connection causing Heka to spit out an error and lose every other message.
* To help balance up long-running connections hitting RRDNS-based VIPs.
Reconnections are based on the successfully processed messages counter, and the config value defaults to 0 (no connection re-establishment, the current behaviour).
> Config option for TcpOutut connection re-establishment

- docker/Dockerfile.final
- docker/build_docker.sh
The EXEC statement will never succeed because of how the debian package places the default config file.
> Bad EXEC for starting up heka container

- docs/source/pluginconfig/logstreamer.rst
Way back logstreamer's default behavior changed (#1066) and this was
addressed by Rob in #1132 by amending CHANGES.txt.
This diff makes the behavior clearer for new-comers by making the note
in the main documentation.
> Document explicitly that logstreamer's log_directory must exist

- CHANGES.txt
- pipeline/queue_buffer.go
created after we look for it directly but before we get the full list
of files from the queue folder.
> Account for the case where the file that matches our lookup id is

- docs/source/config/decoders/scribble.rst
While there, also make a explicit comment regarding the current
implementation of the sandboxed lua decoders, which will discard
previously scribbled fields.
I'm happy to discuss and amend the text if you think it's necessary.
> Add second example to ScribbleDecoder

- cmake/externals.cmake
as highlighted in issue #1329 maybe it is worth bumping the lua sandbox git commit. Tests seem to pass just fine. No lost functionality in here so far.
````
heka$ source build.sh
...
100% tests passed, 0 tests failed out of 26
Total Test time (real) =  22.17 sec
````
> Bump Lua Sandbox (Relates to: #1329)

- CHANGES.txt
- plugins/http/http_output.go
Without requiring the full response is read prior to returning, the
closing of the response body might not work, resulting in many sockets in
the TIME_WAIT state.
> Read the whole http response.

- CHANGES.txt
- pipeline/config.go
> Exit cleanly (vs panic) if we get a config that registers no plugins.

- plugins/elasticsearch/elasticsearch.go
- HTTP status always reported
- HTTP status >= 304 errors reported
> ElasticSearch HTTP output: improve error reporting

- CHANGES.txt
- logstreamer/reader.go
As per #1770, here's the PR against 0.10. I'm glad to see that the same change on 0.10 didn't cause any tests to fail as it did against 0.9.
> Use io.ReadFull to ensure full content is read when checking position hash

- docs/source/config/outputs/tcp.rst
- plugins/tcp/tcp_output.go
This PR adds an option to the TcpOuput plugin that closes the socket after successfully writing a message. This is to deal with TCP servers that close their sockets without SO_LINGER enabled.
I discovered this issue while trying to write a JSON payload to Sensu which closes its side of the TCP connection after reading up to a newline. When that happens, the TCP socket on the Heka side transitions to CLOSE_WAIT and is stuck there until we try and write another message. Here is an example:
```
COMMAND     PID  USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
sensu-cli  4809 sensu   10u  IPv4  85956468      0t0  TCP 127.0.0.1:3030 (LISTEN)
sensu-cli  4809 sensu   11u  IPv4  85956469      0t0  UDP 127.0.0.1:3030 
hekad     11504  root   21u  IPv4 203961716      0t0  TCP …
```
> Add CloseAfterWrite option to the TcpOutput

- pipeline/stat_accum_input.go
Recently encountered that you couldn't add Decoders to StatAccumInput when we wanted to add server fields that generally go into the series name as tags instead for the new InfluxDB schema and tried via adding a ScribbleDecoder and it didn't work! Turned out it was because StatAccumInput was using Inject on the InputRunner instead of the newer Deliver which invokes decoders. :)
My auto-formatting also "corrected" a couple of things in the file, it would seem!
> Changing Inject to Deliver in StatAccumInput to allow Decoders

- CHANGES.txt
- cmd/hekad/config.go
- cmd/hekad/main.go
- docs/source/config/index.rst
- pipeline/pipeline_runner.go
- pipeline/plugin_runners.go
- pipeline/router.go
- sandbox/plugins/sandbox_decoder.go
for back-pressure to be relieved, add `full_buffer_max_retries`
global config setting, exit w/ non-zero exit code on error cases.
> Delay startup when buffered plugin has full buffer to give time

- CHANGES.txt
- pipeline/plugin_runners.go
use it when restarting plugins. Fixes #1756.
> Make sure we explicitly prep the config every time we try to

- plugins/amqp/amqp_input.go
- plugins/amqp/amqp_test.go
This change modifies the Run() method to return something other than
nil when the connection to the AMQP server drops. This is partial fix
for bug #1757.
> Fix restart for the AMQP input plugin

- CHANGES.txt
- logstreamer/reader.go
replaced while LogstreamerInput is holding an open file handle.
Fixes #1199.
> Add safety check for cases where zero-length file is deleted and

- plugins/tcp/tcp_input_test.go
slow VMs, remove duplicate error assertion.
> Longer write deadline so we don't fail so often on TravisCI's

- CMakeLists.txt
- rpm/heka.postinst.in
- rpm/heka.preinst.in
* Introduce pre and post install scripts into the RPM CPack configuration. 
* The scripts closely mimic the Debian installer and:
- create heka user;
- create heka group;
- create heka home folder at /var/run/hekad
- create /etc/heka/conf.d
- copy /usr/share/heka/examples/hekad.toml into 
/etc/heka/conf.d/00-hekad.toml
> Rpm install

- plugins/elasticsearch/encoders.go
- plugins/elasticsearch/encoders_test.go
ESJsonEncoder emits invalid JSON for messages without fields if its
"fields" configuration parameter begins with DynamicFields and contains
at least one other field. In this situation, the second line of output
will begin with '{,'.
This change fixes the problem by altering how ESJsonEncoder.Encode()
decides if it has written any fields.
> Fix ESJsonEncoder bug causing invalid output

- docs/source/config/inputs/http.rst
Updates docs for HTTP Input plugin to correct input name.
Also moves misleadingly placed headers subsection to bottom of list. (Though this is largely personal preference.)
> Update HttpInput docs for version 0.10

- docs/source/config/inputs/kafka.rst
- docs/source/config/outputs/kafka.rst
- plugins/kafka/kafka_input.go
- plugins/kafka/kafka_output.go
This allows `KafkaInput` and `KafkaOutput` to connect to the Kafka brokers over a secure connection. The [server side support](http://kafka.apache.org/documentation.html#security_ssl) for this functionality was recently added in Kafka 0.9.0.0.
I structured the configuration identically to the `TcpOutput` parameters and (speculatively) tagged it as appearing in 0.11.
> Add TLS configuration to KafkaInput/KafkaOutput.

- CHANGES.txt
- cmake/externals.cmake
- plugins/docker/attacher.go
- plugins/docker/client.go
- plugins/docker/docker_event.go
- plugins/docker/docker_log_input.go
This PR is a general cleanup of the Docker input plugin to accomplish three major goals:
1. Don't lose connections to Docker when the daemon is down for a period of time
2. Support the splitter API in this plugin
3. Log what is happening
From running Heka with Docker for quite some time at my previous employer (New Relic) we saw that Heka would lose connections to the Docker daemon if it was down for a period of time (e.g. not a restart but a full stop for minute). This was because the re-connect strategy was to restart the plugin entirely and Heka would give up doing that after a short time. This pR takes a different approach and tries very hard to stay connected to the Docker daemon while also still exiting the plugin on total failure.
Secondly a major drawback of the existing plugin is …
> A major revamp of the DockerLogInput plugin

- docs/source/config/splitters/index_noref.rst
- docs/source/config/splitters/pattern_grouping.rst
- pipeline/all_specs_test.go
- pipeline/config.go
- pipeline/splitters.go
- pipeline/splitters_test.go
We work with a lot of Java and Scala stacktraces and the other options I've tried for supporting them in Heka don't work as well as I'd like. This is an implementation of a regex-based `MultilineSplitter` which works great for our stacktraces. The implementation is that you define a regex to use as the delimiter and a regex used to match lines that should be joined together. It first splits the buffer using the delimiter and then checks each section against the multiline regex to see if it's a match. All lines that are contiguous and match the multiline regex are joined. Because of the multiline nature, it always keeps the delimiter on the EOL.
This is going to be notably slower than the `RegexSplitter` because it has to find many matches on the first pass rather than the first one. …
> Implementation of a multiline splitter
