- CHANGES.txt
- cmd/hekad/main.go
It slightly changes behaviour of hekad so i think it needs @rafrombrc approval.
> Added help parameter to hekad and changed loading of config parameter. Fixes #1239

- CHANGES.txt
- client/client.go
- cmd/heka-flood/main.go
- cmd/heka-inject/main.go
- cmd/heka-logstreamer/main.go
- cmd/heka-sbmgr/main.go
- cmd/heka-sbmgrload/main.go
- cmd/hekad/main.go
- pipeline/config.go
- pipeline/multidecoder.go
- pipeline/net_utils.go
- pipeline/packet_tracking.go
- pipeline/pipeline_runner.go
- pipeline/plugin_runners.go
- pipeline/router.go
@rafrombrc Hi, its my next attempt at fixing #105. Waiting for your input, always grateful for your reviews.
> Redirecting logs to stdout and errors to stderr. Fixes #105

- CHANGES.txt
- sandbox/lua/lua_sandbox.go.in
- sandbox/lua/lua_sandbox_interface.c
- sandbox/lua/lua_sandbox_test.go
- sandbox/lua/testsupport/read_message.lua
- sandbox/lua/testsupport/read_next_field.lua
> Issue 1284 Fix panic on empty byte fields in the sandbox api

- docs/source/config/outputs/file.rst
- plugins/file/file_output.go
(fix #976)
This is my very first golang patch, so please be indulgent ;-)
> Add FileOutput date rotation support

- pipeline/plugin_runners.go
> Fix synchronous decode.

- docs/source/config/inputs/kafka.rst
> Docs: heka -> kafka -> heka example

- cmd/hekad/main.go
- docs/source/config/splitters/index.rst
- pipeline/config.go
- pipeline/splitter_runner.go
- pipeline/splitters.go
checking validation to max_message_size and min_buffer_size
settings.
> Rename `buffer_size` to `min_buffer_size`, add some sanity

- sandbox/plugins/sandbox_decoder.go
This is a legacy construct and it was not being updated in all cases
causing old error messages to be displayed when there was no error.
> Remove the err variable from the SandboxDecoder struct

- CHANGES.txt
- pipeline/splitter_runner.go
- pipeline/splitter_runner_test.go
- plugins/logstreamer/logstreamer_input.go
> Shortbuf infinite loop

- CHANGES.txt
- pipeline/config.go
- pipeline/splitter_runner.go
> Do the `SetSplitterRunner` test in `NewSplitterRunner` instead

- sandbox/lua/lua_sandbox.go.in
- sandbox/lua/lua_sandbox_test.go
- sandbox/lua/testsupport/field_scribble.lua
- sandbox/lua/testsupport/write_message_errors.lua
> Fixes #1380.

- cmd/heka-flood/main.go
- logstreamer/reader.go
- message/message.go
- plugins/file/file_polling_input.go
- plugins/http/http_input.go
- plugins/irc/irc_output.go
- plugins/kafka/kafka_input.go
Please see commit messages for details.
> Code clean up using `go vet`

- CHANGES.txt
- plugins/process/process_input.go
> Reset sync.Once after ProcessInput exits, and treat long-running

- CHANGES.txt
- docs/source/config/outputs/udp.rst
- plugins/udp/udp_output.go
- plugins/udp/udp_output_test.go
> UdpOutput drops message if its size exceeds allowed UDP data size (#1393)

- docs/source/sandbox/module.rst
- pipeline/config.go
- sandbox/lua/encoders/cbuf_librato.lua
- sandbox/lua/encoders/es_payload.lua
- sandbox/lua/modules/elasticsearch.lua
- sandbox/lua/modules/msg_interpolate.lua
Requested by https://github.com/mozilla-services/heka/pull/1420#discussion_r26525940
> Extract message interpolation

- sandbox/lua/decoders/linux_procstat.lua
- sandbox/lua/filters/procstat.lua
add support for processing /proc/stat
https://github.com/mozilla-services/heka/pull/1320
> add procstat processing

- CHANGES.txt
- pipeline/config.go
- pipeline/plugin_runners.go
- pipeline/plugin_runners_test.go
- pipeline/report.go
Hi, it's my first take on sync decoders in reports. @rafrombrc @trink could you review?
Thanks in advance :)
> Decoders in synchronous mode are visible in reports. Fixes #1312

- plugins/udp/udp_input.go
- plugins/udp/udp_input_test.go
In Go, unixgram addresses starting with "@" are treated as
abstract.
Abstract domain sockets do not create a file on the filesystem,
so we omit the chmod and cleanup used with other unixgram
sockets.
Abstract domain sockets are also Linux-specific so we
check runtime.GOOS and behave accordingly.
Fixes #1371.
> Add support for abstract UNIX domain sockets

- pipeline/plugin_runners.go
> Use locks on the makers struct and check for shutdown during

- plugins/process/process_input.go
Closing the CC Stopchan will make ```Wait()``` return.
Need to move the defer's to the InputRunner to avoid closing already closed
channels for the Stdout/stderr decoders.
Closes #1444
> Make RunCmd::Wait() return on Stop()

- CHANGES.txt
- sandbox/plugins/sandbox_manager_filter.go
> Inject a termination message in addition to logging to the

- sandbox/lua/testsupport/encoder_raw.lua
- sandbox/plugins/sandbox_encoder.go
- sandbox/plugins/sandbox_encoders_test.go
> Update the MsgBytes pointer in the copy on write pack

- CHANGES.txt
- pipeline/splitter_runner.go
- pipeline/splitter_runner_test.go
@rafrombrc @trink  could you review?
> Added handling of deliver_incomplete_final to the SplitBytes() in SpliterRunner. Fixes #1455

- CHANGES.txt
- docs/source/sandbox/module.rst
- sandbox/lua/lua_sandbox_test.go
- sandbox/lua/modules/graphite.lua
- sandbox/lua/testsupport/graphite.lua
@rafrombrc @trink could you conduct initial review?
> Issue 1461

- CHANGES.txt
- plugins/http/http_input.go
- plugins/http/http_input_test.go
> Don't overwrite custom user-agent config.

- docs/source/pluginconfig/logstreamer.rst
> fix:docs of ")"

- CHANGES.txt
- cmd/heka-flood/main.go
- docs/source/developing/testing.rst
@rafrombrc @trink could you review?
> Added ability to reconnect after lost connection in heka-flood. Fixes #1536

- CHANGES.txt
- docs/source/config/inputs/httplisten.rst
- plugins/http/http_listen_input.go
- plugins/http/http_listen_input_test.go
https://github.com/mozilla-services/heka/issues/1534
> Adding SSL/TLS support to HttpListenInput #1534

- CHANGES.txt
- pipeline/config.go
- pipeline/plugin_maker.go
- pipeline/plugin_runners_test.go
- plugins/process/process_directory_input.go
- sandbox/plugins/sandbox_filters_test.go
- sandbox/plugins/sandbox_manager_filter.go
> PluginMaker overhaul to remove cached config state.

- CHANGES.txt
- cmake/externals.cmake
- docs/source/config/encoders/esjson.rst
- docs/source/config/encoders/eslogstashv0.rst
- plugins/elasticsearch/coordinates.go
- plugins/elasticsearch/encoders.go
- plugins/elasticsearch/encoders_test.go
- plugins/file/file_output.go
- plugins/payload_encoder.go
- plugins/payload_encoder_test.go
@rafrombrc @trink could you review? Thanks in advance.
> Implemented strftime in PayloadEncoder and ESJsonEncoder (#1508).

- CHANGES.txt
- docs/source/config/inputs/docker_log.rst
- plugins/docker/attacher.go
- plugins/docker/docker_log_input.go
Example:
```toml
[DockerLogInput]
fields_from_env = [ "FOO", "BAR" ]
```
> DockerLogInput: add new `fields_from_env`

- sandbox/lua/encoders/schema_influx_write.lua
https://github.com/influxdb/influxdb/issues/3100
> [encoders] fix influx v0.9 schemata, see

- CHANGES.txt
- docs/source/developing/plugin.rst
- pipeline/plugin_maker.go
- pipeline/splitter_runner.go
- plugins/amqp/amqp_input.go
- plugins/amqp/amqp_test.go
- plugins/file/file_polling_input.go
- plugins/file/file_polling_input_test.go
- plugins/http/http_input.go
- plugins/http/http_input_test.go
- plugins/http/http_listen_input.go
- plugins/http/http_listen_input_test.go
- plugins/kafka/kafka_input.go
- plugins/kafka/kafka_input_test.go
- plugins/logstreamer/logstreamer_input.go
- plugins/logstreamer/logstreamer_input_test.go
- plugins/process/process_input.go
- plugins/process/process_input_test.go
- plugins/tcp/tcp_input.go
- plugins/tcp/tcp_input_test.go
- plugins/udp/udp_input.go
- plugins/udp/udp_input_test.go
> Add 'Done' method to SplitterRunner interface, use it as needed

- dasher/javascript/adapters/sandboxes_adapter.js
- dasher/javascript/collections/plugins.js
- dasher/javascript/collections/sandboxes.js
> Issue #586 sort plugins and sandboxes alphabetically in the dashboard

- CHANGES.txt
- docs/source/config/decoders/index.rst
- docs/source/config/decoders/index_noref.rst
- docs/source/config/decoders/nginx_stub_status.rst
- sandbox/lua/decoders/nginx_stub_status.lua
- sandbox/plugins/sandbox_decoders_test.go
follow up to https://github.com/mozilla-services/heka/pull/1636
> add nginx stub status decoder

- CHANGES.txt
- docs/source/config/inputs/stataccum.rst
- pipeline/stat_accum_input.go
StatsD support it . So i made it happen in heka too. 
And this should help developer to know the how the trend really goes .
> Make StatAccumInput Plugin Support Multi percent_threshold values

- CHANGES.txt
- pipeline/report.go
> Protobuf encode the report messages before injecting them

- docs/source/config/outputs/index.rst
> Add buffering options to the `Common Output Parameters`

- Dockerfile
- docker/Dockerfile
- docker/Dockerfile.final
There was previous work for fixing Docker builds here: #1566 . Work was only done for development environment and the original author hasn't gotten back to feedback.
This PR fixes the development, build, and release Dockerfiles. You should be able to follow the documentation in /docker and get yourself a release image.
> Bring Dockerfile's up to date

- docs/source/config/inputs/amqp.rst
So I got bit by these and figured I could document it. Feel free to reject the PR if you find it more confusing than helpful.
> add extra example to AMQPInput docs

- CHANGES.txt
- sandbox/plugins/sandbox_input.go
> Exit for-loop when stopChan closes

- docs/source/config/common_sandbox_parameter.rst
> Add text indicating that `module_directory` now supports

- docs/source/installing.rst
(cherry picked from commit 5c58445e19f6c09255df497b2089ffe81c54768a)
> Complete Unix prerequisites

- cmake/externals.cmake
- behead_array utility function
- lua_sax updates (NaN mindist, cmake C language restriction)
> Pull in the latest lua_sandbox

- sandbox/lua/decoders/linux_netdev.lua
See https://github.com/mozilla-services/heka/issues/1767 for explanation and caveats
> change netdev decoder output format to split by tags

- CHANGES.txt
- cmd/hekad/config.go
- cmd/hekad/main.go
> Fix global `max_pack_idle` setting

- sandbox/lua/modules/ts_line_protocol.lua
according to docs, supposed to only add specific field names
> relax outer condition

- cmake/externals.cmake
This should fix the issue #1691.
> Pull in the latest gostrftime library

- examples/host_filter.go
since `Recycle` func param has been changed.
> fix compile bug for host_filter example

- cmd/heka-logstreamer/main.go
- docs/source/config/inputs/logstreamer.rst
- logstreamer/filehandling.go
- logstreamer/reader.go
- logstreamer/reader_test.go
- plugins/logstreamer/logstreamer_input.go
feature request by #1482, #1801
some code based on #1486.
> support initial_tail option in LogstreamerInput

- cmd/heka-logstreamer/main.go
- logstreamer/reader.go
> bugfix: initial_tail is failed when file is small than 500 bytes

- plugins/docker/attacher.go
I would like so see the name of the image which is currently logging.
Based on image name I can aggregate application logs.
> added container image to fields for docker input
